### ISSUE TITLE
Implement initial simple system: Exercise 1 in CT19

### ISSUE THREAD

**Issue by ssardina** [COSC1107-CT/pytomata-marker#1]
This is an epic issue to start-up project.

- [x] #2
- [x] #3
- [x] #4
- [ ] 1. Go over each student submissions. each submission has been done programatically, in functions, returning their solution (string, DFA, whatever)
- [ ] 2. Check each submission against the instructor programmed marking functions. each marking function will take the student answers (whatever they are for the question) and will return marks achieved + feedback text to add to report.
- [ ] 3. Produce student report.
